name: deploy

on:
    # 每当 push 到 docs 分支时触发部署
    push:
        branches: [main]
    # 手动触发部署
    workflow_dispatch:

jobs:
    docs-github:
        # 运行在最新版 ubuntu 系统中
        runs-on: ubuntu-latest
        # step 的超时时间
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v2
              with:
                  # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  # 选择要使用的 node 版本
                  node-version: 16.x
                  registry-url: https://registry.npmmirror.com/

            - uses: pnpm/action-setup@v2.2.2
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 7
                  run_install: false

            - name: Get pnpm store directory
              id: pnpm-cache
              run: |
                  echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                  path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install antfu/ni
              run: npm i -g @antfu/ni

            - name: Install dependencies
              run: ni

            # 运行构建脚本
            - name: Build Project-Admin site
              run: nr build

            # 查看 workflow 的文档来获取更多信息
            # @see https://github.com/crazy-max/ghaction-github-pages
            - name: Deploy to GitHub Pages
              uses: crazy-max/ghaction-github-pages@v3
              with:
                  # 部署到 gh-pages 分支
                  target_branch: gh-pages
                  # 部署目录为 Project-Admin 的默认输出目录
                  build_dir: dist
              env:
                  # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
