name: sync

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        # 运行在最新版 ubuntu 系统中
        runs-on: ubuntu-latest
        # step 的超时时间
        timeout-minutes: 10
        steps:
            # 新建一个名为 Sync to Gitee 的步骤
            - name: Sync to Gitee
              # 使用 wearerequired/git-mirror-action@master 获取源码
              uses: wearerequired/git-mirror-action@master
              env:
                  # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
              with:
                  # 注意替换为你的 GitHub 源仓库地址
                  source-repo: git@github.com:liang235/project-admin.git
                  # 注意替换为你的 Gitee 目标仓库地址
                  destination-repo: git@gitee.com:cdl235/project-admin.git

            - name: Build Gitee Pages
              uses: yanglbme/gitee-pages-action@main
              with:
                  # 注意替换为你的 Gitee 用户名
                  gitee-username: cdl235
                  # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
                  gitee-password: ${{ secrets.GITEE_PASSWORD }}
                  # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
                  gitee-repo: cdl235/project-admin
                  # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
                  branch: gh-pages
